version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    restart: on-failure
    volumes:
      - .:/go/src/ticket
    networks:
      - openLetterNetwork
    ports:
      - "80:80"
  postgres:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgres
      - .:/go/src/initdb.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - openLetterNetwork

  redis:
    image: redis
    volumes:
      - /var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - openLetterNetwork

networks:
  openLetterNetwork:
    driver: bridge



